// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.2
//   protoc               v5.28.2
// source: packages/core/src/protos/tank_model.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Vector3, createBaseVector3 } from "./utils";

export const protobufPackage = "blitzkit";

export interface TankModel {
  modules: { [key: string]: ModuleModel };
}

export interface TankModel_ModulesEntry {
  key: string;
  value: ModuleModel | undefined;
}

export interface ModuleModel {
  translation: Vector3;
}

function createBaseTankModel(): TankModel {
  return { modules: {} };
}

export const TankModel: MessageFns<TankModel> = {
  encode(message: TankModel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    Object.entries(message.modules).forEach(([key, value]) => {
      TankModel_ModulesEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TankModel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTankModel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = TankModel_ModulesEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.modules[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TankModel {
    return {
      modules: isObject(object.modules)
        ? Object.entries(object.modules).reduce<{ [key: string]: ModuleModel }>((acc, [key, value]) => {
          acc[key] = ModuleModel.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: TankModel): unknown {
    const obj: any = {};
    if (message.modules) {
      const entries = Object.entries(message.modules);
      if (entries.length > 0) {
        obj.modules = {};
        entries.forEach(([k, v]) => {
          obj.modules[k] = ModuleModel.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TankModel>, I>>(base?: I): TankModel {
    return TankModel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TankModel>, I>>(object: I): TankModel {
    const message = createBaseTankModel();
    message.modules = Object.entries(object.modules ?? {}).reduce<{ [key: string]: ModuleModel }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = ModuleModel.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseTankModel_ModulesEntry(): TankModel_ModulesEntry {
  return { key: "", value: createBaseModuleModel() };
}

export const TankModel_ModulesEntry: MessageFns<TankModel_ModulesEntry> = {
  encode(message: TankModel_ModulesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ModuleModel.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TankModel_ModulesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTankModel_ModulesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ModuleModel.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TankModel_ModulesEntry {
    return {
      key: globalThis.String(assertSet("TankModel_ModulesEntry.key", object.key)),
      value: ModuleModel.fromJSON(assertSet("TankModel_ModulesEntry.value", object.value)),
    };
  },

  toJSON(message: TankModel_ModulesEntry): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ModuleModel.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TankModel_ModulesEntry>, I>>(base?: I): TankModel_ModulesEntry {
    return TankModel_ModulesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TankModel_ModulesEntry>, I>>(object: I): TankModel_ModulesEntry {
    const message = createBaseTankModel_ModulesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ModuleModel.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseModuleModel(): ModuleModel {
  return { translation: createBaseVector3() };
}

export const ModuleModel: MessageFns<ModuleModel> = {
  encode(message: ModuleModel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.translation !== undefined) {
      Vector3.encode(message.translation, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModuleModel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModuleModel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.translation = Vector3.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModuleModel {
    return { translation: Vector3.fromJSON(assertSet("ModuleModel.translation", object.translation)) };
  },

  toJSON(message: ModuleModel): unknown {
    const obj: any = {};
    if (message.translation !== undefined) {
      obj.translation = Vector3.toJSON(message.translation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModuleModel>, I>>(base?: I): ModuleModel {
    return ModuleModel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModuleModel>, I>>(object: I): ModuleModel {
    const message = createBaseModuleModel();
    message.translation = (object.translation !== undefined && object.translation !== null)
      ? Vector3.fromPartial(object.translation)
      : createBaseVector3();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

function assertSet<T>(field: string, value: T | undefined): T {
  if (!isSet(value)) {
    throw new TypeError(`Required field ${field} is not set`);
  }

  return value as T;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
