name: Build Bot

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Prisma
        run: bun run build:prisma

      - name: Build bot
        run: bun run build:bot

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: dist/bot
